name: Equipe Cerveau et Conscience, LSCP
title: Offres de stage  
description: |  
  Ecole Normale Supérieure <br />  
  Equipe Cerveau et Conscience, LSCP <br />  
  Principal investigator: <b>Sid Kouider</b>
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman
gems:
  - jekyll-mentions
