title: |
  Offres de stage 
  LSCP, Equipe 'Cerveau et Conscience'
description: "3 postes : Machine learning, Environnement acoustique 3D, Développeur front-end / web designer"
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
