name: Equipe Cerveau et Conscience, LSCP
title: |
  LSCP, Equipe Cerveau et Conscience  
description: |
  Offres de stage  
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
