name: Equipe Cerveau et Conscience, LSCP
title: Offres de stage  
tagline: |
  "LSCP, Equipe Cerveau et Conscience \n" 
  "Principal investigator: Sid Kouider"
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman
gems:
  - jekyll-mentions
